services:
  mui-react-todo-app:
    build:
      context: .
    container_name: mui-react-todo-app
    hostname: mui-react-todo-app
    tty: true
    volumes:
      - ./:/app
      - mui-react-todo-app-node-modules:/app/node_modules
    ports:
      - 3000:3000
      - 6006:6006
    command: "yarn dev"

volumes:
  mui-react-todo-app-node-modules:
